server:
  port: 9999
  servlet:
    context-path: /rent-house
spring:
  profiles:
    active:
      - dev
  sa-token:
    token-name: satoken
    timeout: 604800
    activity-timeout: -1
    is-concurrent: false
    is-share: false
    token-style: uuid
    is-log: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:dd
    time-zone: GMT+800
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML5
    servlet:
      content-type: text/html
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 0
      logic-not-delete-value: 1
