logging:
  level:
    com.jianglinnana.house: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.5.156.190:3306/rent_house?useUnicode=true&characterEncoding=utf8
    username: root
    password: jianglin19150.Z
